image: Ubuntu1804

branches:
  only:
    - main

init:
  - echo "Installing NVM..."
  - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh | bash
  - export NVM_DIR="$HOME/.nvm"
  - source "$NVM_DIR/nvm.sh"
  - echo "Installing Node.js..."
  - nvm install 16
  - nvm use 16

install:
  - echo "Installing dependencies..."
  - npm install

before_build:
  - rm -rf dist/ 

build_script:
  - echo "Building the project..."
  - npm run build

test_script:
  - echo "Running tests..."
  - npm test

deploy_script:
  - echo "Deploying to GitHub Pages..."
  - cp -r dist/* .  
  - git config user.name "AppVeyor"  
  - git config user.email "ci@appveyor.com"  
  - git config credential.helper "store --file=$HOME/.git-credentials"  
  - echo "https://$GITHUB_TOKEN:x-oauth-basic@github.com" > "$HOME/.git-credentials"  
  - git push origin HEAD:gh-pages  
  - echo "Deployment complete."
